name: Package Application with Pyinstaller

on:
  push:
    tags:
    - 'build-action-test**'
    - '[0-9]+.[0-9]+.[0-9]+'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Package Application
      uses: JackMcKew/pyinstaller-action-windows@main
      with:
        path: .

    - uses: actions/upload-artifact@v2
      with:
        name: Windows Standalone
        path: src/dist/windows
